# Generated by Django 5.2.5 on 2025-09-08 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/additional/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Дополнительное фото',
                'verbose_name_plural': 'Дополнительные фото',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('main_photo', models.ImageField(upload_to='products/main/', verbose_name='Главное фото')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('attributes', models.TextField(blank=True, help_text='Краткое описание атрибутов', verbose_name='Атрибуты')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('size', models.CharField(blank=True, max_length=100, verbose_name='Размер')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='Цвет')),
                ('additional_photos', models.ManyToManyField(blank=True, to='webapp.productphoto', verbose_name='Дополнительные фото')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['name'],
            },
        ),
    ]
