# Generated by Django 5.2.5 on 2025-09-09 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='<UNK> <UNK>'),
        ),
    ]
